//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SummaryGenerator : ISummaryGenerator
{
    public void createInstance()
    {
        throw new NotImplementedException();
    }

    public ISummaryGenerator getInstance()
    {
        throw new NotImplementedException();
    }
}

