//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Author
{
	public virtual object Name
	{
		get;
		set;
	}

	public virtual object Address
	{
		get;
		set;
	}

	public virtual object Description
	{
		get;
		set;
	}

	public virtual object DOB
	{
		get;
		set;
	}

}

