//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Book : Product
{
	public virtual Publisher Publisher
	{
		get;
		set;
	}

	public virtual IEnumerable<Author> Author
	{
		get;
		set;
	}

}

