//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CustomerReview
{
	public virtual object Title
	{
		get;
		set;
	}

	public virtual object Rating
	{
		get;
		set;
	}

	public virtual object DOR
	{
		get;
		set;
	}

	public virtual object Description
	{
		get;
		set;
	}

	public virtual object Comment
	{
		get;
		set;
	}

	public virtual object Helpefulness
	{
		get;
		set;
	}

	public virtual Customer Customer
	{
		get;
		set;
	}

}

