//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Product : Product
{
	public override object Name
	{
		get;
		set;
	}

	public virtual object Cost
	{
		get;
		set;
	}

	public override object DateProduced
	{
		get;
		set;
	}

	public override object Status
	{
		get;
		set;
	}

	public virtual Manufacturer Manufacturer
	{
		get;
		set;
	}

}

