//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ShoppingItem
{
	public virtual object Price
	{
		get;
		set;
	}

	public virtual object Name
	{
		get;
		set;
	}

	public virtual object Image
	{
		get;
		set;
	}

	public virtual object ItemType
	{
		get;
		set;
	}

	public virtual object Discount
	{
		get;
		set;
	}

	public virtual object RemainingCost
	{
		get;
		set;
	}

	public virtual object Quantity
	{
		get;
		set;
	}

	public virtual object ShippingDate
	{
		get;
		set;
	}

	public virtual object ShippingCost
	{
		get;
		set;
	}

	public virtual object Status
	{
		get;
		set;
	}

	public virtual Product Product
	{
		get;
		set;
	}

}

